#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

read $1
echo '-'
echo "-"
echo "-"
echo "-"
echo $1

message="$(cat $1)"
echo '-'
requiredPattern="^(feat:|fix:|perf:|refactor:) .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood>: <what was done>"
  echo "Allowed verbs in imperative mood: feat, fix, refactor, perf"
  echo "Example: feat: login button"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi

yarn lint-staged
